public with sharing class GroupLeader 
{
    public GroupLeader() 
    {

    }

    public String yoLeader(String interaction) 
    {
        // The group leader is a very consistent person who always responds the 
        // same way to conversation starters. Populate this class with conditional
        // code the responds according to the rules below:
        //
        // if you say "Ohana", the Group Leader will respond "Ohana indeed."
        //
        // If you shout "Ohana", the Group Leader will respond "Awesome!"
        //
        // The Group Leader is a very helpful person, so if you ask them a question
        // they will respond "No problem" (NOTE: A the last non-whitespace character of a question
        // is the question mark.
        //
        // If you shout a question at the Group Leader, they will respond "You don't need a microphone!"
        //
        // if you shout, the Group Leader will respond "I'm right here!"
        //
        // if you don't say anything, the Group Leader will respond "Don't be shy, this is a safe place."
        // 
        // If you say anything else, the Group Leeader will respond "That's amazing!"
    }
}
